# Generated by Django 4.1 on 2023-02-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_pack_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='RFID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
